### PR TITLE
fixed some clippy warnings

### PR DESCRIPTION
**Pull request by llogiq**
Just a few style things, but hopefully useful

### CODE REVIEW

**Comment by FredericJacobs** [comment]
Thanks @llogiq!

I'll definitely consider adding clippy once compiler plugins are stable.

**Comment by llogiq** [comment]
If you use rustup.rs, you can directly run clippy with `rustup run nightly cargo rustc --lib --L /path/to/clippy/target/release -Z extra-plugins=clippy` without even needing to do anything to your code.

**Comment by FredericJacobs** [comment]
That's neat! Thanks for the tip.

**Comment by llogiq** [comment]
Glad I can help. :smile:

**Pull request merged**
