### PR TITLE
Minor changes (typos, keep up with rust stable) 

### PR DESCRIPTION
**Pull request by Liamsi**
Nothing big here: Just changes I did locally while skimming through the code: [std::process::exit](https://doc.rust-lang.org/std/process/fn.exit.html) is stable now and one or two typos. Feel free to ignore if not useful.
Looks like a nice job btw :+1:.

### CODE REVIEW

**Comment by FredericJacobs** [comment]
Great @Liamsi. Thanks for the quick code skim.

Since you worked on some of the cothority JVSS code, did you look at the interpolation code an Gf implementation? Thoughts on that?

**Comment by Liamsi** [comment]
Hi FredericJacobs,

no, I didn’t really have a detailed look into the GF generation, nor at the interpolation implementation. Like with the rest of the code I just skimmed through it: I found the way to write the generated code into a rust file (and include it) confusing on first sight but clever (maybe a test that asserts the expected table could help here, might also be exaggerated). 
Anyways, I scanned through it more thoroughly: the generated file (nothinghardcoded.rs) looks fine (the log[0]=0 made me think there must be sth. wrong but the log function looks correct; returns `None` in this case). What I didn’t understand: why to generate `inv`: it is never used (I just removed it locally and everything works as before). I would not generate it, if there are no plans to ever use it (can send you a PR for that later).  The lagrange interpolation looks correct (and exactly like the non-optimized version in the wikipedia article). As it is always only called with zero as a 2nd parameter, one could simplify the interpolation  further by removing it (see here: https://github.com/Liamsi/RustySecrets/commit/c84666aaec3173b4d56bd51fd71dba0393c77ab9)

I wouldn’t trust my opinion (only): My contribution to the cothoritiy’s JVSS code was merely to make it race condition free. The JVSS protocol was recently rewritten by @Daeinar, while @nikkolasg wrote most of it, and he also wrote parts of underlying crypto in dedis’ crypto library necessary for JVSS (so maybe he has more to say). But I would guess that that there are still some levels of abstraction which were already covered by the crypto lib (written by several people at yale and @bford). So I’m sure we didn’t need to take care with the field generation ourselves.

Again: Well done! Was fun reading (and writing) some Rust code again :-)

**Comment by Liamsi** [comment]
Hi again, I'm not sure anymore the gf256 generation/implementation works as it should. I wrote two small tests that checks against the multiplication in GF(2^8) examples here: http://www.site.uottawa.ca/~chouinar/Handout_CSI4138_AES_2002.pdf and they fail. If you have some time I can come by (probably I got sth wrong and the code is fine).

**Comment by FredericJacobs** [comment]
Good idea, I'll add some Gf(2^8) external test vectors and see if those work.

**Comment by Liamsi** [comment]
> Good idea, I'll add some Gf(2^8) external test vectors and see if those work.

My tests failed because I used the examples from vanilla AES (which uses a different polynomial; not 0x11D). I sent you a PR (#6) for the other changes (minor simplifications) I did.

**Pull request merged**
